name: Automated Tests

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
jobs:
  shellcheck:
    name: Shellcheck
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Shellcheck
        uses: ludeeus/action-shellcheck@master
